[target.'cfg(all(target_arch = "arm", target_os = "none"))']
### Flash over usb without external programmer ###
# runner = "picotool load --update --verify --execute -t elf"
### Flash over SWD with probe-rs ###
runner = "probe-rs run --chip RP2040"

[build]
target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "debug"
# EMBASSY_EXECUTOR_TASK_ARENA_SIZE = "180000"